### ISSUE TITLE
Error This page can't be displayed. Contact support for additional information.

### ISSUE THREAD

**Issue by fealvareznicolin** [cop-cos/openapi-sdk-php#1]
I was doing the test that comes by default and it gives me this error.

200 OK
**Error**
Error
--
This page can't be displayed. Contact support for additional information.The EVENT ID is: 6585388175451476151.The SESSION ID is: N/A.页面无法显示。请联系支持人员了解更多信息。事件编号：6585388175451476151.会话编号： N/A.

why is that?

**Comment by fealvareznicolin** [comment]
the error appears when I use api key and production secret key, with the test key I get error 403

**Comment by Chenjp** [comment]
The request was blocked by WAF incorrectly.

**Comment by fealvareznicolin** [comment]
I keep getting 403 error
Client error: `GET https: //api.lines.coscoshipping.com/service/info/tracking/6103622780? NumberType = bl` resulted in a` 403 Forbidden` response: {"message": "You cannot consume this service" } 403 Forbidden {"message": "You cannot consume this service"}

it doesn't matter if I use production or test api key, the result is the same, I can't consume the api

**Comment by Chenjp** [comment]
Please provider us your company name to help us check your privileges later.

**Comment by Chenjp** [comment]
No more information. Close it.
